version: '3'

services:
  default_app: &default_app
    env_file:
      - .env
    working_dir: /app
    image: crystallang/crystal:latest
    volumes:
      - .:/app
    ports:
      - 8080:8080

  app:
    <<: *default_app
    ports:
      - 3000:3000
    command: crystal run src/vih_bot.cr

  play:
    <<: *default_app
    ports:
      - 8080:8080
    command: crystal play --binding 0.0.0.0
